-- MySQL Script generated by MySQL Workbench
-- Fri Jan 28 22:34:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atm_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atm_db` ;

-- -----------------------------------------------------
-- Table `atm_db`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm_db`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `balance` DOUBLE NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idaccount`),
  UNIQUE INDEX `idaccount_UNIQUE` (`idaccount` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atm_db`.`cardmain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm_db`.`cardmain` (
  `idCard` INT NOT NULL AUTO_INCREMENT,
  `idholder` INT NOT NULL,
  `pin` INT NOT NULL,
  `numbers` VARCHAR(45) NOT NULL,
  `tip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCard`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE,
  UNIQUE INDEX `numbers_UNIQUE` (`numbers` ASC) VISIBLE,
  INDEX `idholder_idx` (`idholder` ASC) VISIBLE,
  CONSTRAINT `idholder`
    FOREIGN KEY (`idholder`)
    REFERENCES `atm_db`.`account` (`idaccount`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Datele Cardului de baza';


-- -----------------------------------------------------
-- Table `atm_db`.`cardbusiness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm_db`.`cardbusiness` (
  `idcardbusiness` INT NOT NULL,
  `companyid` INT NULL DEFAULT NULL,
  `maxspendlimit` DOUBLE NULL DEFAULT NULL,
  `currentspendlimit` DOUBLE NULL DEFAULT NULL,
  `last_updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idcardbusiness`),
  UNIQUE INDEX `idcardbusiness_UNIQUE` (`idcardbusiness` ASC) VISIBLE,
  CONSTRAINT `idcardbusiness_FK`
    FOREIGN KEY (`idcardbusiness`)
    REFERENCES `atm_db`.`cardmain` (`idCard`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atm_db`.`carddebit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm_db`.`carddebit` (
  `idcarddebit` INT NOT NULL,
  `maxspendlimit` INT UNSIGNED NOT NULL,
  `currentspendlimit` DOUBLE NULL DEFAULT NULL,
  `last_updated` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idcarddebit`),
  CONSTRAINT `idcarddebit_FK`
    FOREIGN KEY (`idcarddebit`)
    REFERENCES `atm_db`.`cardmain` (`idCard`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atm_db`.`cardstudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm_db`.`cardstudent` (
  `idcardstudent` INT NOT NULL,
  `studying` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcardstudent`),
  CONSTRAINT `idcardstudent_FK`
    FOREIGN KEY (`idcardstudent`)
    REFERENCES `atm_db`.`cardmain` (`idCard`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atm_db`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm_db`.`company` (
  `idcompany` INT NOT NULL AUTO_INCREMENT,
  `cname` VARCHAR(45) NULL DEFAULT NULL,
  `cfunds` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idcompany`),
  UNIQUE INDEX `idcompany_UNIQUE` (`idcompany` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
